### ISSUE TITLE
About vocabulary.txt

### ISSUE THREAD

**Issue by zhiqi-0** [adepierre/caffe-char-rnn#3]
Hi, thank you for your work.
The `vocabulary_62.txt` in launch_files is really the vocabulary list for testing? I find it really strange to be as a vocabulary.

**Comment by adepierre** [comment]
Yes it is. What is strange?

**Comment by zhiqi-0** [comment]
Inside vocabulary.txt, it looks like following:

> First Czen:
> Bfowpcdayuh,mk.AlSYv?RMW'LINg;b!OjV-THEUDPqxJGKQZX

what's this?

**Comment by adepierre** [comment]
Well, as it is named "vocabulary" it is ... the vocabulary used by the network : every character it can use to write words.

**Comment by zhiqi-0** [comment]
OK...I thought it should be words, but now I find you use character for generating words rather than words for generating sentence. Thank you!
